// AUTO-GENERATED from /starsnap-main/starsnap-web/design-system/tokens.json. Do not edit directly.
package com.photo.starsnap.designsystem

import androidx.compose.ui.graphics.Color

object StarSnapColor {
    val canvas = Color(0xFFF6F7FB)
    val surface = Color(0xFFFFFFFF)
    val surfaceSubtle = Color(0xFFEEF1F6)
    val surfaceHover = Color(0xFFF8FAFC)
    val border = Color(0xFFE2E6ED)
    val borderStrong = Color(0xFFCBD5E1)
    val text = Color(0xFF171B24)
    val textSoft = Color(0xFF2A2F3A)
    val textSubtle = Color(0xFF505866)
    val textMuted = Color(0xFF98A1B2)
    val brand = Color(0xFFFFE55B)
    val brandHover = Color(0xFFF5D63B)
    val brandActive = Color(0xFFE0BE2A)
    val brandSoft = Color(0xFFFFF8CF)
    val danger = Color(0xFFDC2626)
    val dangerStrong = Color(0xFFB91C1C)
    val dangerMuted = Color(0xFFF87171)
    val dangerSoft = Color(0xFFFEF2F2)
    val dangerSubtle = Color(0xFFFEE2E2)
    val dangerBorder = Color(0xFFFECACA)
    val success = Color(0xFF059669)
    val successStrong = Color(0xFF166534)
    val successAccent = Color(0xFF34D399)
    val successSoft = Color(0xFFECFDF5)
    val successSubtle = Color(0xFFD1FAE5)
    val successBorder = Color(0xFFBBF7D0)
    val warning = Color(0xFFD97706)
    val warningStrong = Color(0xFF92400E)
    val warningSoft = Color(0xFFFFFBEB)
    val warningBorder = Color(0xFFFED7AA)
    val info = Color(0xFF2563EB)
    val infoStrong = Color(0xFF1D4ED8)
    val infoMuted = Color(0xFF60A5FA)
    val infoSoft = Color(0xFFEFF6FF)
    val infoSubtle = Color(0xFFDBEAFE)
    val infoBorder = Color(0xFFBFDBFE)
    val cyan = Color(0xFF0E7490)
    val cyanSoft = Color(0xFFECFEFF)
    val cyanHover = Color(0xFFCFFAFE)
    val purple = Color(0xFF7E22CE)
    val purpleSoft = Color(0xFFFAF5FF)
    val purpleHover = Color(0xFFF3E8FF)

    val yellow50 = Color(0xFFFFFDF2)
    val yellow100 = Color(0xFFFFF8CF)
    val yellow200 = Color(0xFFFFF2A8)
    val yellow300 = Color(0xFFFFEB7A)
    val yellow400 = Color(0xFFFFE55B)
    val yellow500 = Color(0xFFF5D63B)
    val yellow600 = Color(0xFFE0BE2A)
    val yellow700 = Color(0xFFB89818)
    val yellow800 = Color(0xFF8A7210)
}
